{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "resources": [
    "resources.yaml"
  ],
  "configMapGenerator": [
    {
      "name": "prometheus-config",
      "namespace": "monitoring",
      "files": [
        "prometheus.yml",
        "alerts.yml",
        "alerts.test.yml"
      ]
    },
    {
      "name": "grafana-provisioning",
      "namespace": "monitoring",
      "files": [
        "datasources.yml",
        "dashboards.yml"
      ]
    },
    {
      "name": "grafana-dashboard",
      "namespace": "monitoring",
      "files": [
        "api-dashboard.json"
      ]
    }
  ]
}
