deployment:
  replicas: 1
ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik
providers:
  kubernetesCRD:
    enabled: false
  kubernetesIngress:
    enabled: true
  kubernetesGateway:
    enabled: false
service:
  spec:
    type: ClusterIP
ports:
  websecure:
    expose:
      default: false
ingressRoute:
  dashboard:
    enabled: false
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi
